# Generated by Django 5.1 on 2024-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(),
        ),
    ]
