# Generated by Django 5.1 on 2024-09-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
