# Generated by Django 5.1 on 2024-09-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_order_profile_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('upi', 'upi'), ('net_banking', 'net_banking'), ('cash_on_delivery', 'cash_on_delivery')], default='cash_on_delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='totel_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
