# Generated by Django 5.1 on 2024-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='no_of_prducts',
            new_name='no_of_products',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
