# Generated by Django 5.1 on 2024-09-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_no_of_prducts_category_no_of_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discription',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
