# Generated by Django 5.1 on 2024-09-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_remove_products_discription_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stoke',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
