# Generated by Django 5.1 on 2024-09-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_products_stoke_products_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stoke',
            new_name='stock',
        ),
    ]
