# Generated by Django 5.1 on 2024-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_rename_stoke_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
