# Generated by Django 5.1 on 2024-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_products_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
