# Generated by Django 5.1 on 2024-09-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_otp_from_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
