# Generated by Django 5.1 on 2024-09-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
